// 1 next js er global CSS
import './globals.css'
// 2 next js a built-in google font asey
import { Inter } from 'next/font/google'

// **** next js a HTML er kono EXISTENCE NAAAAIII

// next js surui hy "layout.js" file diye, thik jmn react suru hy "main.js" diyte, BUT amra chaile 1ta next project a MULTIPLE "layout" rakhte pari

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

// ei "RootLayout" name CHANGE kra jabe NAAA
export default function RootLayout({ children }) {
  return (
    // tag "html" hoile this is actually JSX
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  )
}
